import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>My Nav Bar</h1>
        </nav>
        {children}
        </body>
    </html>
  )
}

//---------Notes-------
//This will show up on all pages 
//so if we want a nav bar on all the pages this is where we would set that up 
//this is the parent layout that will apply to all of the children 
//you can add layout for the individual directories as well to have layout for the files in the specific directory